solution: solved the 3rd challenge of array methods (3)
The-Code-Dose/js-challenges pull request #10
Opened 2023-08-31 17:47 UTC by PushpakRaut

What does this PR do
This PR Solved the 3rd challenge of array-methods

#Screenshot

![image](https://github.com/The-Code-Dose/js-challenges/assets/85230759/15170e26-09ac-4a29-b491-ad1087d57193)

#Changes

solution update.

2023-08-31 20:05 UTC, PushpakRaut commented
updated this one as well.

2023-09-01 17:48 UTC, thecodedose requested changes

2023-09-01 17:48 UTC, thecodedose commented on solutions/array_methods/3.js
> +console.log(TotalCost)
```suggestion
const totalCost = ingredients.reduce((acc, { quantity, price }) => acc + quantity * price, 0);

console.log(totalCost);
```

2023-09-02 09:54 UTC, PushpakRaut commented
I have fixed the changes you asked for!
now the output is changed :
![image](https://github.com/The-Code-Dose/js-challenges/assets/85230759/f783b450-84dc-4e08-9b85-c7ff84a31aba)


code snippet: 
![image](https://github.com/The-Code-Dose/js-challenges/assets/85230759/20233b1c-2b32-4e6e-a52f-f527a8c247c6)

2023-09-19 10:38 UTC, merged